ISIS3510-202410-Team23/SwiftApp

FoodBookApp/DAO/Firebase/ExampleDAOFirebase.swift
FoodBookApp/Persitence/Firebase.swift

Refactors Firebase.swift to use Singleton pattern. Now accessed at different DAOs through the `shared` attribute
Closes #29

[FIX] Apply singleton pattern to Firebase Client

---

FoodBookApp.xcodeproj/project.pbxproj

- Changed the name of the app when downloading it (the "App" at the end is gone)
- Closes #32

[UI] Change app name

---

FoodBookApp/Models/Review.swift
FoodBookApp/Services/AuthService.swift
FoodBookApp/UI/Views/Bookmarks/BookmarksView.swift
FoodBookApp/UI/Views/CreateReview/CreateReview2View.swift
FoodBookApp/UI/Views/CreateReview/CreateReview2ViewModel.swift
FoodBookApp/UI/Views/SpotDetail/ReviewsView.swift
FoodBookApp/Utils/Utils.swift

Commit d087d6e93d28abca7ca8bd4da789e600cf1b5c62
* AuthDataResult model now has property `name`
* Adds example usage to Bookmarks view (see below)
Pending
* user model changes on reviews so both email and display name are stored
* considerations on the issue #58 discussion
* considerations if new sign-in methods are added
Closes #58

[FIX] Display names instead of emails on reviews

---

FoodBookApp.xcodeproj/xcshareddata/xcschemes/FoodBookApp.xcscheme
FoodBookApp/Services/BackendService.swift

Moves the backend url to the environment variables. 
This should be setup within the included schema file at `FoodBookApp.xcodeproj/xcshareddata/xcschemes/FoodBookApp.xcscheme`
To check go to Product > Scheme > Edit Scheme. 
On the Run tab select Arguments and in the Environment Variables section you should see the follwing:
Please review that the ForYou page works on your devices/emulators!
Closes #68 
TBD: Left a TODO for better error handling once we define the type of errors.

[FIX] Backend URL as Environment Variable

---

FoodBookApp/Handlers/NotificationHandler.swift

Changes the text to
```
Header: Hungry? It's lunchtime!
Text: Looks like you're on campus, find a spot or rate the one you've been at!
```
Closes #64

[FIX] Change Context Aware notification text to match

---

FoodBookApp/Info.plist
FoodBookApp/Services/AuthService.swift
FoodBookApp/UI/Views/Bookmarks/BookmarksView.swift

closes #73 
- I am not entirely sure if this code should all go directly on the View, so if not I will do the refactoring
- This introduces the use of FaceID and TouchID for unlocking the bookmarks view, for introducing another type of authentication to our app.
https://github.com/ISIS3510-202410-Team23/SwiftApp/assets/77981728/f0967681-f220-4b32-8763-ad98297515c6

[FU] adds local authentication to bookmarks

---

FoodBookApp/Models/Spot.swift
FoodBookApp/UI/Components/HCategoryList.swift
FoodBookApp/UI/Components/SpotCard.swift
FoodBookApp/UI/Views/Browse/BrowseView.swift
FoodBookApp/UI/Views/SpotDetail/SpotDetailView.swift
FoodBookApp/Utils/Utils.swift

Updated the UI as follows based on the comments on the Viva Voce.
closes #59

[FIX] Update UI to show category aggregation and top only top categories in browse.

---

FoodBookApp.xcodeproj/project.pbxproj
FoodBookApp/Models/ReviewDraft.swift
FoodBookApp/SQLite/DBManager.swift
FoodBookApp/UI/Views/CreateReview/CreateReview1View.swift
FoodBookApp/UI/Views/CreateReview/CreateReview2View.swift
FoodBookApp/UI/Views/User/UserView.swift

- Closes #84 
- Creates a local copy of an image for review draft with FileManager
- Deletes all images stored if user logs out
- 🚨 To test on your phone/simulator, please **log out** so DB can be created again (the DB is used to store the image path)
- In the next comment you'll see a ss of the review uploaded
- This concludes my local storage feature
https://github.com/ISIS3510-202410-Team23/SwiftApp/assets/69609680/71bf446e-dd97-45f7-9e85-082a5cdf2029

[FEATURE] Save a local copy of the image to file storage

---

FoodBookApp/UI/Views/CreateReview/CreateReview1View.swift

- Closes #105 
- Now you can have a draft w/ just the image. However, remember that to access the view with the image if you have to select a category.
https://github.com/ISIS3510-202410-Team23/SwiftApp/assets/69609680/ad85c338-f190-4694-ad13-56c7f4607357

[FIX] Draft can be created with just the image

---

FoodBookApp/UI/Views/CreateReview/CreateReview1View.swift
FoodBookApp/UI/Views/CreateReview/CreateReview1ViewModel.swift
FoodBookApp/UI/Views/SpotDetail/SpotDetailView.swift
FoodBookApp/UI/Views/SpotDetail/SpotDetailViewModel.swift

- Closes #109 
- The fetch for the categories is now done while also fetching a spot's detail, which allows users to start a review without having to wait for the categories to load.
https://github.com/ISIS3510-202410-Team23/SwiftApp/assets/69609680/d301972c-1612-410e-9c12-20bdfccb9e48

[FIX] Fetch categories when fetching spot

---

FoodBookApp/Handlers/NotificationHandler.swift
FoodBookApp/Models/ReviewDraft.swift
FoodBookApp/SQLite/DBManager.swift
FoodBookApp/UI/Views/Browse/BrowseView.swift
FoodBookApp/UI/Views/CreateReview/CreateReview1View.swift
FoodBookApp/UI/Views/CreateReview/CreateReview2View.swift
FoodBookApp/UI/Views/CreateReview/CreateReview2ViewModel.swift
FoodBookApp/UI/Views/SpotDetail/SpotDetailView.swift
FoodBookApp/UI/Views/User/UserView.swift
FoodBookApp/Utils/Utils.swift

- Closes #125 
- Adds eventual connectivity for when a review is uploaded with no connection.
- Uses temporary local storage to store reviews.
- When you test it, 🚨**LOG OUT**🚨 first. This is because I changed the DB so it needs to be rebuilt. In fact, I actually suggest uninstalling the app and installing it again to fully delete the old DB from your storage. 
Lmk if you have any questions or want changes made 
https://github.com/ISIS3510-202410-Team23/SwiftApp/assets/69609680/617d352b-27fd-4b9d-8069-c7e89bb386bd

[FEATURE] Eventual connectivity for review upload

---

FoodBookApp/UI/Views/Login/LoginView.swift
FoodBookApp/UI/Views/Login/LoginViewModel.swift
FoodBookApp/Utils/SignInGoogleHelper.swift

* If a user takes longer than 45 seconds to complete the sign in flow (for example if they are signing in and connection is to slow for google to processes it) then the view google's UI is shown is dismissed and a message is shown (completes and closes #115)
* Solution was a combination of threading, GCD and Observable objects/variable
Demo video with happy path, cancel path (or any other error that is caught in the VM) and timeout path below: 
https://github.com/ISIS3510-202410-Team23/SwiftApp/assets/61592394/9ef4f2d2-7843-4c6d-90de-064fc60bc0ae
Note for the demo timeout was to set to 5 seconds, in the PR it has the 45 mentioned above

[FEATURE] Add timeout to login flow (once in the browser) using multi-threading

---

FoodBookApp.xcodeproj/project.pbxproj
FoodBookApp/Models/Cache/HardcodedSpots.swift
FoodBookApp/UI/Views/Content/ContentViewModel.swift
FoodBookApp/UI/Views/SpotDetail/SpotDetailView.swift

- Closes #134 
- Adds eventual connectivity for a spot detail, specifically when a user opens this view w/o connection
- Adds alert when spot detail's info had been loaded but the user had no connection and attempts to leave a review
- Fixed browse spots cache edge cases (hopefully)

[FEATURE] EC: spot detail, reviews and leave review + cache fix

---

FoodBookApp.xcodeproj/project.pbxproj
FoodBookApp/Utils/Utils.swift

- Closes #91 
- Adds multithreading to sort categories using GCD
- Keep in mind, the app executes with no error, but there was one time an error showed up, even when the build succeded. I'll create a new issue if this error comes up again. This error didn't block the app tho, it's weird

[FEATURE] Category sorting multithreading

---

FoodBookApp/UI/Views/Bookmarks/BookmarksView.swift

* Closes #156 
* Also updates the styling to match other messages. 👯

[FIX] More descriptive message when user has bookmarks but data cannot be fetched

---

FoodBookApp/UI/Components/SpotCard.swift
FoodBookApp/UI/Views/Bookmarks/BookmarksView.swift
FoodBookApp/UI/Views/ForYou/ForYouView.swift
FoodBookApp/Utils/Utils.swift

- Closes #148 
- EC reviews are uploaded when accessing the ForYou and Bookmarks views now, hopelly fixing the problem Boris found. Not entirely sure this is the solution bc I've tried to recreate the problem multiple times and nothing worked. The only thing I remember is that, before uploading the review, he was in the Bookmarks view, so that's why I coded this solution. If we somehow stumble upon the problem again, I'll open another issue
- This PR also changes the progress view in the hard coded spots to a static image.

[BUGFIX] EC reviews uploaded twice

---

FoodBookApp/Services/BookmarksService.swift
FoodBookApp/UI/Views/Bookmarks/BookmarksView.swift
FoodBookApp/UI/Views/Content/ContentView.swift

* Fixes #173 
🔧 Re-instantiates `bookmarksMansger` on login-dismiss
🧹  Cleans up cache and id's loaded in RAM once user logs out
🔐 Adds `private` modifier to `savedBookmarksId` and adds get methods for it

[PATCH] Bookmarks functionality between users restores

---

FoodBookApp/FoodBookApp.swift
FoodBookApp/Handlers/NotificationHandler.swift
FoodBookApp/UI/Views/Login/LoginView.swift

- Closes #110 
- Changes notification permission timing, so now it's not done after login, it's done every app launch. Please remember that the `askPermission()` function only asks permission if it hasn't been asked before, not every time it's called, meaning that it won't ask permission every time the app is opened.
- Fixes bug where uninstalling and re-installing the app deleted the permission but didn't ask for it again
- Although it doesn't use the same strategy as the location permission (see the comment I made inside the issue), it has the same timing, so both permissions will be asked subsequently 

[FIX] Notification permission timing

---

FoodBookApp/Utils/Utils.swift

- Closes #179 
- Fixes multithreading for the sorting categories function. Previously, threads were created to append categories to the array but not sorting them
Lmk if you have any questions or want changes made. Apologies for the oversight!

[FIX] Categories sorting function

---

FoodBookApp/Utils/Utils.swift

- Closes #181 
- Reverts the sorting function to the previous version because the new one causes the app to freeze

[PATCH] Reverts sorting function to previous version

---

FoodBookApp/UI/Views/CreateReview/CreateReview1View.swift
FoodBookApp/UI/Views/CreateReview/CreateReview2View.swift

- Adds arrows to switch between title and body fields
- Adds 'OK' to close keyboard
- x button just clears the field now instead of closing the keyboard as well
- This wasn't an issue but I decided to add it since it made the UX much better
In the video I long press the buttons so you can see what's happening. Irl, however, you don't need to do this
https://github.com/ISIS3510-202410-Team23/SwiftApp/assets/69609680/c0d5de10-3015-4ab5-a9d6-7501f065ea12

[FEATURE] Easier keyboard access for create review views

---

FoodBookApp/SQLite/DBManager.swift
FoodBookApp/UI/Views/Bookmarks/BookmarksView.swift
FoodBookApp/UI/Views/Browse/BrowseView.swift
FoodBookApp/UI/Views/Content/ContentView.swift
FoodBookApp/UI/Views/ForYou/ForYouView.swift

- Closes #185 
- I found what was causing the issue and it was because it wasn't using a singleton, so I fixed that 
- Changes where  `uploadReviews()` is called, now it's not on the Browse, ForYou and Bookmarks views, it's on the ContentView file, which avoids the repetition of code. It also adds an onChange modifier so the user doesn't have to manually change views to upload the reviews
- For some reason, this change also makes the reviews be uploaded in every (or at least almost every) view if connection is recovered, which is good!! This basically means that wherever the user is, if they have connection, the reviews will be uploaded. I'm guessing it's because I'm using an onChange and the views are on top of each other (?)

[PATCH] EC reviews uploaded twice (v2)

---

FoodBookApp/UI/Components/HCategoryList.swift
FoodBookApp/UI/Components/ReviewCard.swift
FoodBookApp/UI/Views/Bookmarks/BookmarksView.swift
FoodBookApp/UI/Views/Browse/BrowseView.swift
FoodBookApp/UI/Views/BugReport/BugReportView.swift
FoodBookApp/UI/Views/CreateReview/CreateReview1View.swift
FoodBookApp/UI/Views/CreateReview/CreateReview2View.swift
FoodBookApp/UI/Views/ForYou/ForYouView.swift
FoodBookApp/UI/Views/Reviews/ReviewsView.swift
FoodBookApp/UI/Views/SpotDetail/SpotDetailView.swift
FoodBookApp/UI/Views/UserReviews/UserReviewsView.swift

- Closes #203 
- Changes all ForEach loops that looped over an array to indexed loops. 
Bonus:
- Adds disabling logic for 'Done' button in CreateReview2View
Lmk if you have any questions or want changes made 
The scenario involved creating a review and then checking its upload in the Reviews view. Notice the slight decrease in time spent for each thread that took # seconds (ignore ms, the difference is irrelevant).
**Before M.O.**
**After M.O.**

[FIX] M.O. (most) ForEach loops are now indexed

---

FoodBookApp/ServiceAdapter/Firebase/SpotSAFirebase.swift

* Fixes #205 
Changes the logic of fetching in reviews for a spot. Instead of being serial, this is done using `TaskGroups` where each `Task` has the responsibility of fetching a review given it's snapshot. From a user's perspective this significantly reduced the loading time in Spots with more reviews.
**Changes made**
1. **Refactored Query Execution:**
- **Before MO:** 
```swift
for reviewRef in spot.reviewData.userReviews {
let review = try await self.getReview(ref: reviewRef)
reviews.append(review)
}
```
- **After MO:** 
```swift
// Use a task group to fetch reviews concurrently
try await withThrowingTaskGroup(of: Review.self) { group in
for reviewRef in spot.reviewData.userReviews {
group.addTask {
return try await self.getReview(ref: reviewRef)
}
}
// Collect all reviews
for try …
```

[FIX] Review fetching with TaskGroups
