FoodBookApp.xcodeproj/project.pbxproj
FoodBookApp/DAO/CategoryDAO.swift
FoodBookApp/DAO/Firebase/CategoryDAOFirebase.swift
FoodBookApp/Repositories/Category/CategoryRepository.swift
FoodBookApp/Repositories/Category/CategoryRepositoryImpl.swift
FoodBookApp/UI/Views/CreateReview/CreateReview1ViewModel.swift

Completes fetch of categories from database. I populated the DB with the options that were hardcoded into the ViewModel. 
Closes #42 
Note: 
* There might be conflicts with #14, that PR should be merged first since its the more complex one @Laurarestrepo03

[FEATURE] Fetch Categories from Backend

---

FoodBookApp/ContentView.swift
FoodBookApp/UI/Views/LoginView.swift

[BUGFIX] Fix mistake in location services call

---

FoodBookApp.xcodeproj/project.pbxproj

[FIX] Remove FirebaeAppCheck from dependencies

---

FoodBookApp.xcodeproj/project.pbxproj
FoodBookApp/Repositories/Category/CategoryRepositoryImpl.swift
FoodBookApp/Repositories/Review/ReviewRepository.swift
FoodBookApp/Repositories/Review/ReviewRepositoryImpl.swift
FoodBookApp/Repositories/Spot/SpotRepository.swift
FoodBookApp/Repositories/Spot/SpotRepositoryImpl.swift
FoodBookApp/ServiceAdapter/CategorySA.swift
FoodBookApp/ServiceAdapter/Firebase/CategorySAFirebase.swift
FoodBookApp/ServiceAdapter/Firebase/ReviewSAFirebase.swift
FoodBookApp/ServiceAdapter/Firebase/SpotSAFirebase.swift
FoodBookApp/ServiceAdapter/ReviewSA.swift
FoodBookApp/ServiceAdapter/SpotSA.swift

Fixes design pattern naming error identified during the Viva Voce
Closes #61

[FIX] Refactor DAO naming to SA

---

FoodBookApp/UI/Views/SpotDetail/SpotDetailView.swift

[FIX] Show number of reviews in 'See more'

---

FoodBookApp/Services/LocationService.swift
FoodBookApp/UI/Views/Bookmarks/BookmarksView.swift

Moves geofence creation to constructor of LocationServices to ensure it is always created.
Closes #66

[FIX] Assure geofence creation.

---

FoodBookApp.xcodeproj/project.pbxproj
FoodBookApp/Services/NetworkService.swift
FoodBookApp/UI/Views/Bookmarks/BookmarksView.swift

**Implements a services that monitors the network status and publishes them variables accesible throughout the application.**
A small demo is available in the BookmarksView, this can be used as the boilerplate for using the service in other parts of the application: 
The variables mentioned earlier are: 
* `isOnline` - true when path.status is "satisfied"
* `isLowConnection` - true when path.isConstrained is true. ⚠️ I haven't been able to simulate the conditions so this state is activated
* `isUnavailable` - true when path.status is either "unsatisfied" or "requiresConnection".  📌  it might be necessary to separate this into two later on, but for now i believe this will suffice
Closes #78 
Note: I am using a DispatchQueue so this runs in the background, on another thread. I believe this …

[FEATURE] Network Service for monitoring status and implementing EC patterns

---

FoodBookApp/UI/Views/Browse/BrowseView.swift

closes #57 
Here's how it looks!

[FEATURE] Eventual connectivity message when no hits in search

---

FoodBookApp/Persistence/Firebase.swift

```
let settings = FirestoreSettings()
settings.cacheSettings = MemoryCacheSettings()
self.db = Firestore.firestore()
self.db.settings = settings
```

[FEATURE] Disable firebase cache

---

FoodBookApp.xcodeproj/project.pbxproj
FoodBookApp/Models/ReviewDraft.swift
FoodBookApp/SQLite/DBManager.swift
FoodBookApp/UI/Views/Bookmarks/BookmarksView.swift
FoodBookApp/UI/Views/CreateReview/CreateReview1View.swift
FoodBookApp/UI/Views/CreateReview/CreateReview2View.swift
FoodBookApp/UI/Views/SpotDetail/SpotDetailView.swift

- Closes #85 
- Creates local db to store review drafts
- Checks if there is a draft for a spot. If so, user is presented with two options: create from draft or new one
- Allows only one draft per spot
- **No** local storage for image, will be done later
**THIS VIDEO HAS SOUND 🔊**
https://github.com/ISIS3510-202410-Team23/SwiftApp/assets/69609680/690a9858-68d3-42aa-8955-295aad1b7d07

[FEATURE] Local database for review drafts

---

FoodBookApp.xcodeproj/xcshareddata/xcschemes/FoodBookApp.xcscheme
FoodBookApp/Services/BackendService.swift
FoodBookApp/UI/Views/Browse/BrowseView.swift
FoodBookApp/UI/Views/ForYou/ForYouView.swift
FoodBookApp/UI/Views/ForYou/ForYouViewModel.swift
SQLite.xcodeproj/project.pbxproj
SQLite.xcodeproj/xcshareddata/xcschemes/SQLite Mac.xcscheme
SQLite.xcodeproj/xcshareddata/xcschemes/SQLite iOS.xcscheme
SQLite.xcodeproj/xcshareddata/xcschemes/SQLite tvOS.xcscheme
SQLite.xcodeproj/xcshareddata/xcschemes/SQLite visionOS.xcscheme
SQLite.xcodeproj/xcshareddata/xcschemes/SQLite watchOS.xcscheme

CLOSING ISSUES:
- closes #63 
- closes #60 
DESCRIPTION:
- Now, if a user has not left any reviews, the ForYou page won't recommend anything (the backend throws a 404 not found) therefore, the UI had to change to adapt to this
- Browse and ForYou now have loading screens for better user experience.
DEMO:
- Sorry that it takes a long time to change accounts, ignore that, although it is relevant since the first account does have reviews and the second one does not.
ADDITIONAL:
- It is merged with the last develop version (up to this commit: [50d4ad4491bfa790f5d188ea89d669d04e30fc2e](https://github.com/ISIS3510-202410-Team23/SwiftApp/commit/50d4ad4491bfa790f5d188ea89d669d04e30fc2e))
https://github.com/ISIS3510-202410-Team23/SwiftApp/assets/77981728/8e2297bd-8db4-46e3-8739-ade3eaa42470

[FIX] Encourage user to leave reviews and more

---

FoodBookApp.xcodeproj/project.pbxproj
FoodBookApp/UI/Views/Bookmarks/BookmarksView.swift
FoodBookApp/UI/Views/ContentView.swift
FoodBookApp/UI/Views/RootView.swift
FoodBookApp/UI/Views/User/UserView.swift

Implements the profile view and frees up the bookmarks view for feature implementation.
https://github.com/ISIS3510-202410-Team23/SwiftApp/assets/61592394/83718af7-9967-431a-857f-39011f6d5f1a
Closes #98

[FEATURE] Profile View and Restored Sign Out 

---

FoodBookApp/UI/Views/SpotDetail/SpotDetailView.swift

- Closes #103 
- Shows a spinning wheel while data for a spot's detail is being fetched (using ProgressView)
https://github.com/ISIS3510-202410-Team23/SwiftApp/assets/69609680/d1810423-5c8b-4f21-84f5-957163f4684e

[FIX] Spinning wheel when loading spot detail

---

FoodBookApp/Services/NetworkService.swift
FoodBookApp/UI/Views/Login/LoginView.swift
FoodBookApp/UI/Views/Login/LoginViewModel.swift

* Disables the sign in button when there is no connection or the connection is low. 
* Re-enables the button once connection is restored
* Adds proper error management to the different cases identified.
* ⚠️ These cases were identified and implemented during testing in different conditions, including network speed and removing connections at different points during the process. However, the testing is no exhaustive, if new cases are found they should be reported as an issue and tagged as a bug 🐛
* Closes #79
https://github.com/ISIS3510-202410-Team23/SwiftApp/assets/61592394/c00336f7-5e0a-4db3-8c88-d7e79513280e

[FEATURE] EC messages in the LoginView

---

FoodBookApp.xcodeproj/project.pbxproj
FoodBookApp/Services/BookmarksService.swift
FoodBookApp/UI/Views/Bookmarks/BookmarksView.swift
FoodBookApp/UI/Views/Bookmarks/BookmarksViewModel.swift

* Completes the visualization of the bookmarks based on the saved Ids; 
* Uses `NSCache` as the mechanism to store said saved bookmarks locally.
* Implements the **Cache then network** functionality, the VM will check if there is data loaded on cache and use that if available. Otherwise it will fetch the data from Firebase.
* The bookmarks functionality itself is complete, I'll be adding the corresponding logs to the backend for answering the BQ later on.
Video includes all functionality, including the use of cache when offline (if available).
https://github.com/ISIS3510-202410-Team23/SwiftApp/assets/61592394/09d994e6-3132-488b-8ff6-60174f5db2b8
Closes #89

[FEATURE] Completed bookmarks implementation with caching strategy

---

FoodBookApp/Services/BookmarksService.swift
FoodBookApp/UI/Components/SpotCard.swift
FoodBookApp/UI/Views/Bookmarks/BookmarksView.swift
FoodBookApp/UI/Views/Bookmarks/BookmarksViewModel.swift
FoodBookApp/UI/Views/ContentView.swift
FoodBookApp/UI/Views/Login/LoginView.swift
FoodBookApp/UI/Views/Login/LoginViewModel.swift
FoodBookApp/UI/Views/User/UserView.swift
FoodBookApp/Utils/Error.swift
FoodBookApp/Utils/SignInGoogleHelper.swift

* Fixes the issue where the image in the user profile view did not have a fixed size and would take up the whole container, causing weird rendering issues as reported by @Laurarestrepo03. Closes #101  🛠️ 
* Fixes an issues where the saved bookmark id's were being shared by different users. Now they are each stored with a separate key so each person that logs in keeps their saved items.  Closes #117  🔒 
* Fixing this issue required migrating the `BookmarksService` from a singleton pattern to be an an environment object. (If you have questions regarding this change lmk and i'll document thoroughly. 👩🏼‍💻 
* Finally, fixed the formatting on the EC alter for the LoginView so they show title and description and are more readable.
* Partially implements #115, still missing the trigger for the …

[FIX] User image size and bookmarks user mangement

---

FoodBookApp.xcodeproj/project.pbxproj
FoodBookApp/Repositories/BookmarksUsage/BookmarksUsageRepository.swift
FoodBookApp/Repositories/BookmarksUsage/BookmarksUsageRepositoryImpl.swift
FoodBookApp/ServiceAdapter/BookmarksUsageSA.swift
FoodBookApp/ServiceAdapter/Firebase/BookmarksUsageSAFirebase.swift
FoodBookApp/Services/BookmarksService.swift

* Implements the business question on #93 (Closes #93)
* When a user goes from 0 to 1 bookmarks the usage is set to true.
* When a user goes from 1 to 0, it is set to false. 
* All other cases don't trigger an update in the firebase to avoid unnecessary updates to the data.
Demo below: 
https://github.com/ISIS3510-202410-Team23/SwiftApp/assets/61592394/80fc3244-41b8-40b3-bfd7-e16e67d7ca4e

[FEATURE] Bookmarks BQ

---

FoodBookApp/SQLite/DBManager.swift
FoodBookApp/UI/Views/SpotDetail/SpotDetailView.swift

My last PR (#126) didn't include this last commit, my bad!

[REFACTOR] Missing commits

---

FoodBookApp/UI/Views/Content/ContentView.swift
FoodBookApp/UI/Views/RootView.swift
FoodBookApp/UI/Views/User/UserView.swift

CLOSES #94 
- This saves in local storage using a .json file the search history of the user, while showing it to them. 
- It only does so when the user hits the "search" button on the keyboard
https://github.com/ISIS3510-202410-Team23/SwiftApp/assets/77981728/16772789-a7e8-428a-8e99-be26182b3a72

[FEATURE] Search history

---

FoodBookApp/UI/Views/Content/ContentViewModel.swift
FoodBookApp/UI/Views/ForYou/ForYouView.swift

- closes #139 
- this implements an EC message for when cache is empty and network is unavailable for FYP. please take a look at it in the following demo
- this also alligns messages with @JuanCamFalla on flutter app.
if you have any questions, or want any changes made, let me know asap.
https://github.com/ISIS3510-202410-Team23/SwiftApp/assets/77981728/806daa2d-ddf6-485a-8772-1869d860b800

[FEATURE] adds EC message for unavailable network and cache in FYP

---

FoodBookApp.xcodeproj/project.pbxproj
FoodBookApp/Repositories/SearchUsage/SearchUsageRepository.swift
FoodBookApp/Repositories/SearchUsage/SearchUsageRepositoryImpl.swift
FoodBookApp/ServiceAdapter/Firebase/SearchUsageSAFirebase.swift
FoodBookApp/ServiceAdapter/SearchUsageSA.swift
FoodBookApp/UI/Views/Content/ContentView.swift
FoodBookApp/UI/Views/Content/ContentViewModel.swift
FoodBookApp/UI/Views/User/UserView.swift
FoodBookApp/UI/Views/User/UserViewModel.swift

This PR implements the functionality of saving to firebase the search terms a user sends. It adds a bunch of files, but that is because it implements new ViewModels and Repositories. You can see how this works by looking at the demo below. So as Laura says, if you have any questions or want any changes made, let me know!
TODO:
CLOSING:
- closes #155 
https://github.com/ISIS3510-202410-Team23/SwiftApp/assets/77981728/5ce315bd-48ff-48d6-a8f2-1c60241a3687

[FIX] Upload search terms to firebase

---

FoodBookApp.xcodeproj/project.pbxproj
FoodBookApp/Services/AuthService.swift
FoodBookApp/UI/Views/Content/ContentView.swift
FoodBookApp/UI/Views/Content/ContentViewModel.swift

Please try this on your own devices and let me know if it works, it should display different ForYou pages when changing users. 
- closes #170

[PATCH] Fetching is done also when leaving login view

---

FoodBookApp/UI/Views/Browse/BrowseView.swift
FoodBookApp/UI/Views/Content/ContentView.swift
FoodBookApp/UI/Views/Content/ContentViewModel.swift
FoodBookApp/UI/Views/User/UserViewModel.swift

- This restores that progress view when fetching. It is my fault it went missing since I was assigning it outside the task, making it complete first. (Sorry!)
- It also impedes the app from uploading search items if it is null, now firebase won't have a bunch of empty documents.
- Try it out and lmk if you still experience any bugs!
CLOSES #176

[PATCH] Minor: restore progress view

---

FoodBookApp.xcodeproj/project.pbxproj
FoodBookApp/UI/Components/SpotCard.swift
FoodBookApp/UI/Views/Bookmarks/BookmarksView.swift
FoodBookApp/UI/Views/CreateReview/CreateReview2View.swift
FoodBookApp/UI/Views/ForYou/ForYouView.swift
FoodBookApp/UI/Views/SpotDetail/SpotDetailView.swift
FoodBookApp/UI/Views/User/UserView.swift

This changes a lot of stuff that was mentioned on the viva voce. 
- The local authentication flow does not interrupt the verification of the review first. 
- There's tips now for for you view and spot detail, so the user has more context on what is going on. In the user view I included a button that will always show the tips. This is only meant to show them for debug purposes, if you close the app session they should be dismissed.
- Images won't stay on progress view forever
If you have any issues, encounter any bugs, or want any changes made, let me know!
CLOSING ISSUES:
- closes #150 
- closes #154 
- closes #184
- closes #187 
SCREENSHOTS:

[FIX] Changes requested in viva voce 

---

FoodBookApp.xcodeproj/project.pbxproj
FoodBookApp/Repositories/Review/ReviewRepository.swift
FoodBookApp/Repositories/Review/ReviewRepositoryImpl.swift
FoodBookApp/ServiceAdapter/Firebase/ReviewSAFirebase.swift
FoodBookApp/ServiceAdapter/ReviewSA.swift
FoodBookApp/UI/Components/TextFieldWithLimit.swift
FoodBookApp/UI/Views/ReviewReport/ReportReviewView.swift
FoodBookApp/UI/Views/ReviewReport/ReviewReportViewModel.swift
FoodBookApp/UI/Views/SpotDetail/ReviewsView.swift
FoodBookApp/UI/Views/SpotDetail/SpotDetailView.swift

* Closes #168 
* 🆕  Implements a view for creating a report about a review
* 🔢   The information is sent to firebase using a `Task` and a fire and forget strategy so the UI isn't blocked by this operation.
* 📶  Adds EC, a report cannot be sent if the user is not connect
Here's the demo with the happy path: 
https://github.com/ISIS3510-202410-Team23/SwiftApp/assets/61592394/32302b49-e863-4acc-9c52-7ae9cc1ead4c
(Btw, sorry for the low quality I had to compress it a lot to be under 10MB 😔)
Other fixes: 
* Removes custom rectangle in the `ReviewView` sheet and replaces it with the default using a modifier on the sheet. 
* Integrates the custom TextFieldWithLimit component
Feature by @mar-cas3 & @juanyepesp

[FEATURE] Review Reporting

---

FoodBookApp.xcodeproj/project.pbxproj
FoodBookApp/Handlers/NotificationHandler.swift
FoodBookApp/UI/Views/Content/ContentView.swift
FoodBookApp/UI/Views/CreateReview/CreateReview2View.swift
FoodBookApp/UI/Views/Settings/SettingsView.swift

- Closes #164 
- Adds settings view as a sheet and includes a form for notification and authentication settings
- Adds the logic behind the settings, i.e., what happens when they turn on/off the toggles
- Uses UserDefaults to store these preferences
(This vidoe does not include the authentication section, it's in a comment below)
https://github.com/ISIS3510-202410-Team23/SwiftApp/assets/69609680/c858b052-6bbb-4b07-b0b0-836ea841acfe
Feature by @mar-cas3 & @Laurarestrepo03

[FEATURE] Settings view

---

FoodBookApp/UI/Views/User/UserView.swift

[FIX] Remove debug buttons 

---

FoodBookApp.xcodeproj/project.pbxproj
FoodBookApp/UI/Components/SpotCard.swift
FoodBookApp/UI/Views/User/UserView.swift

CLOSING ISSUES:
- closes #196 
DESCRIPTION:
This includes a new package that will cache all images of a spot and from the user view. Yay!
SCREENSHOTS:

[FEATURE] Image caching

---

FoodBookApp/UI/Views/Browse/BrowseView.swift
FoodBookApp/UI/Views/BugReport/BugReportView.swift
FoodBookApp/UI/Views/ReviewReport/ReportReviewView.swift
FoodBookApp/UI/Views/UserReviews/UserReviewsView.swift
FoodBookApp/UI/Views/UserReviews/UserReviewsViewModel.swift

**DESCRIPTION:**
This PR includes a lot of fixes, including:
- hot categories wont show if people want to search stuff
- userReviews view now has reviews sorted
- same EC message for reviewReport
- offline indicator on BugReport
**CLOSING ISSUES**
- closes #197
- closes #195 
- closes #199
If you have any questions or want any changes made, let me know!

[FIX] EC and other standarizaitons

---

FoodBookApp/ServiceAdapter/Firebase/ReviewSAFirebase.swift

This pull request refactors the `getUserReviews` method in `ReviewSAFirebase` to enhance memory management and avoid potential memory leaks. The changes focus on scoping variables more effectively, introducing proper error handling, and improving control flow.
- fixes #201
1. **Refactored Query Execution:**
- **Before MO:** 
```swift
let snapshot = try await collection.whereField("user", isEqualTo: ["id": username, "name": name]).getDocuments()
```
The query was executed and the `snapshot` obtained in a single step, which could lead to leaks.
- **After MO:** 
```swift
let query = collection.whereField("user", isEqualTo: ["id": username, "name": name])
let snapshot = try await query.getDocuments()
```
The query is now created and executed in separate steps, ensuring clearer management of …

[FIX] Separate `getUserReview()` logic

---

FoodBookApp/UI/Views/BugReport/BugReportView.swift
FoodBookApp/UI/Views/ReviewReport/ReportReviewView.swift
FoodBookApp/UI/Views/User/UserView.swift
FoodBookApp/UI/Views/UserReviews/UserReviewsView.swift

* Fixes #207 
* Required text fields in Bug Report and Review Reports now check if the text is empty (ie. only spaces or new lines) and disable the corresponding button until filled
* Changes the button text in the User profile to 'My Reviews'
https://github.com/ISIS3510-202410-Team23/SwiftApp/assets/61592394/86afabf0-be68-4b2d-b6f0-7e43dd51d13b

[PATCH] Pre-Release fixes
